import { PillarData, QuadrantData } from '@/types';

export const PILLARS: PillarData[] = [
  {
    id: 1,
    axis: 'governance',
    name: 'Governança',
    questions: [
      'Existe encarregado de dados (DPO) formalmente nomeado e com atribuições definidas?',
      'Existe política institucional de proteção de dados aprovada pela alta direção?',
      'Existe comitê ou grupo de trabalho de governança de dados?',
      'As responsabilidades sobre o tratamento de dados pessoais estão formalmente definidas?',
      'A política de privacidade é revisada e atualizada periodicamente?',
      'Existe programa formal e estruturado de adequação à LGPD?',
      'Contratos com fornecedores e parceiros incluem cláusulas de proteção de dados?',
      'A alta direção apoia e financia ativamente as iniciativas de privacidade?',
      'Existe processo formal de gestão de mudanças com avaliação de impactos em privacidade?',
      'Os riscos de privacidade são reportados periodicamente à alta direção?',
      'Existe orçamento dedicado ao programa de privacidade e proteção de dados?',
      'A organização possui assessoria jurídica especializada em proteção de dados?',
    ],
  },
  {
    id: 2,
    axis: 'governance',
    name: 'Inventário de Dados',
    questions: [
      'Existe mapeamento completo dos dados pessoais tratados pela organização?',
      'Existe registro de atividades de tratamento (ROPA) atualizado?',
      'Os dados pessoais estão classificados por nível de sensibilidade?',
      'As bases legais para cada operação de tratamento estão identificadas?',
      'O ciclo de vida completo dos dados pessoais está documentado?',
      'Existe política de retenção e descarte seguro de dados pessoais?',
      'Os dados transferidos a terceiros e fornecedores estão mapeados?',
      'O inventário de dados é revisado ao menos anualmente?',
      'Existe processo de avaliação de novos dados antes de iniciar o tratamento?',
      'Os sistemas de TI que tratam dados pessoais estão identificados e documentados?',
      'Existe controle de compartilhamento de dados com órgãos externos?',
      'Dados pessoais de menores de idade possuem controles específicos?',
    ],
  },
  {
    id: 3,
    axis: 'security',
    name: 'Segurança da Informação',
    questions: [
      'Existe controle de acesso baseado em perfil e função (menor privilégio)?',
      'Dados sensíveis são protegidos com criptografia em trânsito e em repouso?',
      'Existe processo formal de detecção, resposta e notificação de incidentes?',
      'Existe política de segurança da informação documentada e vigente?',
      'São mantidos logs de auditoria para acessos a dados pessoais?',
      'Existe plano de continuidade de negócios contemplando dados pessoais?',
      'São realizados testes de vulnerabilidade e/ou pentest periodicamente?',
      'Existe gestão de segurança para dispositivos móveis e acesso remoto?',
      'Existe processo de classificação e proteção de informações confidenciais?',
      'Os sistemas críticos possuem autenticação multifator (MFA)?',
      'Existe processo formal de descarte seguro de mídias e equipamentos?',
      'São realizados backups regulares com testes periódicos de restauração?',
    ],
  },
  {
    id: 4,
    axis: 'security',
    name: 'Direitos do Titular',
    questions: [
      'Existe canal oficial e acessível para solicitação de direitos pelos titulares?',
      'Existe procedimento documentado para atender solicitações dos titulares?',
      'Existe processo para exclusão ou anonimização de dados a pedido?',
      'Existe processo implementado para portabilidade de dados pessoais?',
      'O prazo de resposta ao titular está definido e é respeitado (até 15 dias)?',
      'As solicitações dos titulares são registradas e rastreadas sistematicamente?',
      'O consentimento é coletado de forma granular, específica e documentada?',
      'Existe processo implementado para revogação do consentimento?',
      'Existe aviso de privacidade claro nos pontos de coleta de dados?',
      'São fornecidas informações claras sobre o tratamento no momento da coleta?',
      'Existe processo de notificação de titulares em caso de incidente de segurança?',
      'O atendimento ao titular possui indicadores de desempenho monitorados?',
    ],
  },
  {
    id: 5,
    axis: 'governance',
    name: 'Cultura e Treinamento',
    questions: [
      'Existe programa de capacitação em LGPD para todos os colaboradores?',
      'Os treinamentos são realizados ao menos uma vez por ano?',
      'Existe programa de conscientização contínua em privacidade?',
      'São realizadas auditorias periódicas de conformidade com a LGPD?',
      'O conceito de Privacy by Design é aplicado em novos projetos?',
      'A privacidade é avaliada na aquisição ou desenvolvimento de novos sistemas?',
      'Existe processo de avaliação de impacto à proteção de dados (DPIA/RIPD)?',
      'Auditorias geram planos de ação com prazo e responsáveis definidos?',
      'Existe treinamento de privacidade no processo de integração de novos colaboradores?',
      'Existe canal interno para colaboradores reportarem violações de privacidade?',
      'Os resultados do programa de privacidade são comunicados regularmente?',
      'Existe política de privacidade para os próprios colaboradores?',
    ],
  },
];

export const QUADRANTS: QuadrantData[] = [
  {
    id: 1,
    name: 'Risco Crítico',
    range: [0, 30],
    color: '#E24B4A',
    textColor: '#791F1F',
    bgColor: '#FCEBEB',
    borderColor: '#E24B4A',
    situation: 'Alta exposição jurídica e operacional',
    action:
      'Implante governança mínima com urgência: nomeie um DPO, crie uma política básica de privacidade, inicie o mapeamento de dados pessoais e estabeleça um canal de atendimento ao titular.',
    nextQuadrant: 'Conformidade Inicial',
    nextSteps: [
      'Nomear o DPO formalmente e definir atribuições',
      'Criar e publicar política de privacidade',
      'Iniciar mapeamento de dados pessoais (data mapping)',
      'Estabelecer canal de atendimento ao titular',
      'Realizar treinamento básico de LGPD para todos os colaboradores',
    ],
  },
  {
    id: 2,
    name: 'Conformidade Inicial',
    range: [31, 60],
    color: '#EF9F27',
    textColor: '#412402',
    bgColor: '#FAEEDA',
    borderColor: '#EF9F27',
    situation: 'Conformidade parcial e fragmentada',
    action:
      'Estruture formalmente os processos de governança. Integre TI, jurídico e áreas de negócio em uma gestão coordenada. Complete o inventário de dados e fortaleça os controles de segurança.',
    nextQuadrant: 'Governança Estruturada',
    nextSteps: [
      'Completar o inventário de dados e elaborar o ROPA',
      'Implementar controle de acesso baseado em perfil',
      'Estruturar formalmente a gestão de incidentes de segurança',
      'Formalizar as bases legais de cada operação de tratamento',
      'Fortalecer os controles de segurança da informação',
    ],
  },
  {
    id: 3,
    name: 'Governança Estruturada',
    range: [61, 90],
    color: '#1D9E75',
    textColor: '#04342C',
    bgColor: '#E1F5EE',
    borderColor: '#1D9E75',
    situation: 'Boa aderência à LGPD',
    action:
      'Consolide os controles e evolua para gestão contínua de privacidade. Implemente Privacy by Design, realize DPIAs e fortaleça a cultura organizacional de privacidade em toda a organização.',
    nextQuadrant: 'Excelência em Privacidade',
    nextSteps: [
      'Implementar Privacy by Design em novos projetos',
      'Realizar DPIAs regularmente',
      'Automatizar processos de governança de dados',
      'Fortalecer programa de cultura e conscientização',
      'Implementar monitoramento contínuo de conformidade',
    ],
  },
  {
    id: 4,
    name: 'Excelência em Privacidade',
    range: [91, 120],
    color: '#378ADD',
    textColor: '#042C53',
    bgColor: '#E6F1FB',
    borderColor: '#378ADD',
    situation: 'Privacidade integrada à estratégia organizacional',
    action:
      'Mantenha e evolua o programa. Invista em automação, benchmarking entre instituições e posicionamento como referência em proteção de dados no setor público.',
    nextQuadrant: null,
    nextSteps: [],
  },
];

export const MAX_SCORE = PILLARS.length * 12 * 2; // 120
